### ISSUE TITLE
Error doing job in update_values

### ISSUE THREAD

**Issue by gonzalo1059** [miguelangellv/ha-balance-neto#41]
Since I updated HA to 2026.7.2 I get the following on the HA log:

26-07-11 19:52:35.210 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (task: None)
Traceback (most recent call last):
  File "/config/custom_components/balance_neto/sensor.py", line 99, in update_values
    await grid_balance.update_values()
  File "/config/custom_components/balance_neto/sensor.py", line 236, in update_values
    self.hass.states.get(self._import_id).state,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'state'

Thanks

**Comment by piaassek** [comment]
If you are getting this error, here is a quick fix you can apply right now:

### How to fix it:

1. Open Home Assistant and open the file:
   `/config/custom_components/balance_neto/sensor.py`
   *(using **Studio Code Server**, **File Editor**, or SAMBA/SSH)*.

2. Select everything in that file (`Ctrl + A`) and replace it completely with this fixed code:

<details>
<summary>Click here to expand the fixed sensor.py code</summary>

```python
"""Create and add sensors to Home Assistant."""

from __future__ import annotations

from datetime import date, datetime, timedelta
import logging
from typing import TYPE_CHECKING, Any, Mapping

import pytz
from typing_extensions import override

from homeassistant.components.sensor import (
    RestoreEntity,
    SensorDeviceClass,
    SensorEntity,
    SensorEntityDescription,
    SensorStateClass,
)
from homeassistant.const import EVENT_HOMEASSISTANT_STARTED
from homeassistant.core import callback
from homeassistant.helpers.event import (
    EventStateChangedData,
    async_track_point_in_time,
    async_track_state_change_event,
)

from .const import GRID_EXPORT, GRID_IMPORT, HOURLY, MAX_DIFF, OFFSET, PERIOD

if TYPE_CHECKING:
    from decimal import Decimal

    from homeassistant.config_entries import ConfigEntry
    from homeassistant.core import HomeAssistant
    from homeassistant.helpers.entity_platform import AddEntitiesCallback
    from homeassistant.helpers.typing import EventType, StateType

EXPORT_DESCRIPTION = SensorEntityDescription(
    key="net_exported",
    icon="mdi:home-export-outline",
    name="Net exported",
    translation_key="net_exported",
    has_entity_name=True,
    native_unit_of_measurement="kWh",
    device_class=SensorDeviceClass.ENERGY,
    state_class=SensorStateClass.TOTAL_INCREASING,
    suggested_display_precision=2,
)

IMPORT_DESCRIPTION = SensorEntityDescription(
    key="net_imported",
    icon="mdi:home-import-outline",
    name="Net imported",
    translation_key="net_imported",
    has_entity_name=True,
    device_class=SensorDeviceClass.ENERGY,
    native_unit_of_measurement="kWh",
    state_class=SensorStateClass.TOTAL_INCREASING,
    suggested_display_precision=2,
)

BALANCE_DESCRIPTION = SensorEntityDescription(
    key="net_balance",
    icon="mdi:scale-balance",
    name="Net Balance",
    translation_key="net_balance",
    has_entity_name=True,
    native_unit_of_measurement="kWh",
    suggested_display_precision=2,
    state_class=SensorStateClass.MEASUREMENT,
)

_LOGGER = logging.getLogger(__name__)


# pylint: disable=too-many-locals
async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry, async_add_entities: AddEntitiesCallback) -> None:
    """Initialise sensors and add to Home Assistant."""
    offset = entry.data[OFFSET]
    period = entry.data[PERIOD]
    import_id = entry.data[GRID_IMPORT]
    export_id = entry.data[GRID_EXPORT]
    grid_import = GridNetSensor(IMPORT_DESCRIPTION, f"{entry.entry_id}-import")
    grid_export = GridNetSensor(EXPORT_DESCRIPTION, f"{entry.entry_id}-export")

    grid_balance = BalanceSensor(
        description=BALANCE_DESCRIPTION,
        import_sensor=grid_import,
        export_sensor=grid_export,
        import_id=import_id,
        export_id=export_id,
        unique_id=f"{entry.entry_id}-balance",
    )

    async_add_entities([grid_import, grid_export, grid_balance])

    minutes = 60 if period == HOURLY else 15

    async def update_values(_event: EventType[EventStateChangedData]) -> None:
        await grid_balance.update_values()

    async_track_state_change_event(hass, import_id, update_values)
    async_track_state_change_event(hass, export_id, update_values)

    _LOGGER.debug(
        "Starting Balance Neto with %s for import and %s for export",
        import_id,
        export_id,
    )

    @callback
    async def update_totals_and_schedule(_now: datetime) -> None:
        await grid_balance.update_totals()
        async_track_point_in_time(hass, update_totals_and_schedule, _now + timedelta(minutes=minutes))

    async def first_after_reboot(_now: datetime) -> None:
        await grid_export.after_reboot()
        await grid_import.after_reboot()

    now = datetime.now(tz=pytz.UTC).replace(second=0, microsecond=0)

    next_minutes = minutes - now.minute % minutes
    next_reset = now.replace(second=0) + timedelta(minutes=next_minutes) - timedelta(seconds=offset)

    async_track_point_in_time(hass, update_totals_and_schedule, next_reset)
    hass.bus.async_listen_once(EVENT_HOMEASSISTANT_STARTED, first_after_reboot)


class GridNetSensor(SensorEntity, RestoreEntity):
    """Grid (Import o Export) sensor."""

    def __init__(self, description: SensorEntityDescription, unique_id: str) -> None:
        """Initialize values."""
        super().__init__()
        self._state = 0
        self._attrs: Mapping[str, Any] = {}
        self._attr_unique_id = unique_id
        self.entity_description = description
        self._reboot = None

    @override
    async def async_added_to_hass(self) -> None:
        _LOGGER.debug("Added %s", self._attr_unique_id)
        if (last_sensor_data := await self.async_get_last_state()) is not None:
            self._state = float(last_sensor_data.state)

    @property
    @override
    def extra_state_attributes(self) -> Mapping[str, Any] | None:
        return {
            "Reboot": self._reboot,
        }

    @property
    @override
    def native_value(self) -> StateType | date | datetime | Decimal:
        return self._state

    async def update_value(self, value: float) -> None:
        """Update with balance."""
        self._state = float(self._state) + value
        self.async_write_ha_state()
        _LOGGER.debug("Updating value %f for %s", self._state, self._attr_unique_id)

    async def after_reboot(self) -> None:
        """Set after reboot."""
        self._reboot = datetime.now(tz=pytz.UTC).isoformat()
        self.async_write_ha_state()


class BalanceSensor(SensorEntity, RestoreEntity):
    """Net Balance Sensor."""

    # pylint: disable=too-many-instance-attributes, too-many-arguments
    def __init__(
        self,
        *,
        description: SensorEntityDescription,
        import_sensor: GridNetSensor,
        export_sensor: GridNetSensor,
        import_id: str,
        export_id: str,
        unique_id: str,
    ) -> None:
        """Initialise values."""
        super().__init__()
        self._import = 0
        self._export = 0
        self._import_offset = 0
        self._import_id = import_id
        self._export_offset = 0
        self._export_id = export_id
        self._import_sensor = import_sensor
        self._export_sensor = export_sensor
        self._state = 0
        self._attrs: Mapping[str, Any] = {}
        self._attr_unique_id = unique_id
        self.entity_description = description

    @override
    async def async_added_to_hass(self) -> None:
        await super().async_added_to_hass()
        if (last_sensor_data := await self.async_get_last_state()) is not None:
            self._state = last_sensor_data.state
            self._import = last_sensor_data.attributes.get("Import", 0)
            self._export = last_sensor_data.attributes.get("Export", 0)
            self._import_offset = last_sensor_data.attributes.get("Import Offset", 0)
            self._export_offset = last_sensor_data.attributes.get("Export Offset", 0)

        self.async_write_ha_state()

    @property
    @override
    def native_value(self) -> StateType | date | datetime | Decimal:
        return self._state

    @property
    @override
    def extra_state_attributes(self) -> Mapping[str, Any] | None:
        return {
            "Import": self._import,
            "Export": self._export,
            "Import Offset": self._import_offset,
            "Export Offset": self._export_offset,
        }

    async def _update_value(self) -> None:
        self._state = (self._export - self._export_offset) - (self._import - self._import_offset)
        _LOGGER.debug("Actual Balance %f", self._state)
        self.async_write_ha_state()

    async def update_values(self) -> None:
        """Update Net Balance state."""
        import_entity = self.hass.states.get(self._import_id)
        export_entity = self.hass.states.get(self._export_id)

        import_raw = import_entity.state if import_entity is not None else None
        export_raw = export_entity.state if export_entity is not None else None

        _LOGGER.debug("Import (%s): %s", self._import_id, import_raw)
        _LOGGER.debug("Export (%s): %s", self._export_id, export_raw)

        if import_raw is None or export_raw is None:
            return

        import_state = self._as_number(import_raw)
        export_state = self._as_number(export_raw)

        if import_state is None or export_state is None:
            return

        if self._import_offset == 0:
            self._import_offset = import_state

        diff = import_state - self._import_offset
        if diff > MAX_DIFF or diff < 0:
            self._import_offset = import_state

        if self._export_offset == 0:
            self._export_offset = export_state

        diff = export_state - self._export_offset
        if diff > MAX_DIFF or diff < 0:
            self._export_offset = export_state

        _LOGGER.debug(
            "Updating Balance Neto. Actual Import %f, Export %f. Import offset %f, Export offset %f",
            import_state,
            export_state,
            self._import_offset,
            self._export_offset,
        )

        self._import = import_state
        self._export = export_state

        await self._update_value()

    async def update_totals(self) -> None:
        """Update Net Total values."""
        value = float(self._state)
        _LOGGER.debug("Updating net values. Balance %f", value)
        self._import_offset = self._import
        self._export_offset = self._export
        if value > 0:
            await self._export_sensor.update_value(value)
        else:
            await self._import_sensor.update_value(-value)

        await self._update_value()

    def _reset(self) -> None:
        self._import_offset = 0
        self._export_offset = 0

    @staticmethod
    def _as_number(value: Any) -> float | None:
        if value is None or value in ("unknown", "unavailable"):
            return None
        try:
            return float(value)
        except (ValueError, TypeError):
            return None

**Comment by gonzalo1059** [comment]
> If you are getting this error, here is a quick fix you can apply right now:
> ### How to fix it:
> 
>     1. Open Home Assistant and open the file:
>        `/config/custom_components/balance_neto/sensor.py`
>        _(using **Studio Code Server**, **File Editor**, or SAMBA/SSH)_.
> 
>     2. Select everything in that file (`Ctrl + A`) and replace it completely with this fixed code:
> 
> 
> Click here to expand the fixed sensor.py code

That fixed the error. Thanks a lot
